# Generated by Django 5.0.9 on 2024-11-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="banner_images/")),
                ("title", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "link_url",
                    models.URLField(
                        blank=True, help_text="Optional link URL", null=True
                    ),
                ),
            ],
        ),
    ]
