# Generated by Django 5.0.9 on 2024-10-28 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baseuser",
            name="phone",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
