# Generated by Django 5.0.9 on 2024-10-28 11:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_customuser_delete_baseuser"),
        ("admin", "0003_logentry_add_action_flag_choices"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("wagtailadmin", "0005_editingsession_is_editing"),
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtaildocs", "0013_delete_uploadeddocument"),
        ("wagtailimages", "0026_delete_uploadedimage"),
        ("wagtailusers", "0013_userprofile_density"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CustomUser",
            new_name="BaseUser",
        ),
    ]
