# Generated by Django 5.0.9 on 2024-10-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_rename_customuser_baseuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baseuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
