# Generated by Django 5.0.9 on 2024-10-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_remove_baseuser_phone_remove_candidate_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baseuser",
            name="username",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
