# Generated by Django 5.0.9 on 2024-10-28 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_alter_baseuser_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="member",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidate",
                to="accounts.member",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="phone",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
