# Generated by Django 5.0.9 on 2024-11-01 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_rename_region_member_constituency_member_district_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="candidate",
            old_name="party_affiliation",
            new_name="district",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="member",
        ),
        migrations.AddField(
            model_name="candidate",
            name="age",
            field=models.PositiveIntegerField(default=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="candidate",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="candidate_images/"
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="party",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="candidate",
            name="user",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidate",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
