# Generated by Django 5.0.9 on 2024-11-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_rename_party_affiliation_candidate_district_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidate",
            name="user",
        ),
        migrations.AddField(
            model_name="candidate",
            name="first_name",
            field=models.CharField(default="jhon", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="candidate",
            name="last_name",
            field=models.CharField(default="Doe", max_length=100),
            preserve_default=False,
        ),
    ]
