# Generated by Django 5.0.9 on 2024-11-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0013_remove_candidate_user_candidate_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="address",
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name="candidate",
            name="education",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="candidate",
            name="fathers_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="candidate",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female"), ("other", "Other")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
