# Generated by Django 5.0.9 on 2024-11-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0016_candidate_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="phone",
            field=models.CharField(default="0000000000", max_length=15),
            preserve_default=False,
        ),
    ]
