# Generated by Django 5.0.9 on 2024-11-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0017_candidate_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
