# Generated by Django 5.0.9 on 2024-11-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0021_alter_member_district"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="district",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Anuradhapura", "Anuradhapura"),
                    ("Badulla", "Badulla"),
                    ("Batticaloa", "Batticaloa"),
                    ("Colombo", "Colombo"),
                    ("Digamadulla", "Digamadulla"),
                    ("Galle", "Galle"),
                    ("Gampaha", "Gampaha"),
                    ("Hambantota", "Hambantota"),
                    ("Jaffna", "Jaffna"),
                    ("Kalutara", "Kalutara"),
                    ("Kandy", "Kandy"),
                    ("Kegalle", "Kegalle"),
                    ("Kurunegala", "Kurunegala"),
                    ("Matale", "Matale"),
                    ("Matara", "Matara"),
                    ("Moneragala", "Moneragala"),
                    ("Nuwara Eliya", "Nuwara Eliya"),
                    ("Polonnaruwa", "Polonnaruwa"),
                    ("Puttalam", "Puttalam"),
                    ("Ratnapura", "Ratnapura"),
                    ("Trincomalee", "Trincomalee"),
                    ("Vanni", "Vanni"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="district",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Anuradhapura", "Anuradhapura"),
                    ("Badulla", "Badulla"),
                    ("Batticaloa", "Batticaloa"),
                    ("Colombo", "Colombo"),
                    ("Digamadulla", "Digamadulla"),
                    ("Galle", "Galle"),
                    ("Gampaha", "Gampaha"),
                    ("Hambantota", "Hambantota"),
                    ("Jaffna", "Jaffna"),
                    ("Kalutara", "Kalutara"),
                    ("Kandy", "Kandy"),
                    ("Kegalle", "Kegalle"),
                    ("Kurunegala", "Kurunegala"),
                    ("Matale", "Matale"),
                    ("Matara", "Matara"),
                    ("Moneragala", "Moneragala"),
                    ("Nuwara Eliya", "Nuwara Eliya"),
                    ("Polonnaruwa", "Polonnaruwa"),
                    ("Puttalam", "Puttalam"),
                    ("Ratnapura", "Ratnapura"),
                    ("Trincomalee", "Trincomalee"),
                    ("Vanni", "Vanni"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
