# Generated by Django 5.0.9 on 2024-11-04 13:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0023_candidate_biography"),
    ]

    operations = [
        migrations.RenameField(
            model_name="member",
            old_name="Nic",
            new_name="nic",
        ),
    ]
