# Generated by Django 5.0.9 on 2024-11-06 08:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0025_district"),
    ]

    operations = [
        migrations.DeleteModel(
            name="District",
        ),
    ]
