# Generated by Django 5.0.9 on 2024-11-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0027_district"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="temp_district",
            field=models.ForeignKey(
                null=True, blank=True, to="accounts.District", on_delete=models.SET_NULL
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="temp_district",
            field=models.ForeignKey(
                null=True, blank=True, to="accounts.District", on_delete=models.SET_NULL
            ),
        ),
    ]
