# Generated by Django 5.0.9 on 2024-11-07 12:52

from django.db import migrations


def migrate_to_temp_district(apps, schema_editor):
    Member = apps.get_model("accounts", "Member")
    Candidate = apps.get_model("accounts", "Candidate")
    District = apps.get_model("accounts", "District")

    # Migrate Member districts
    distinct_member_districts = Member.objects.values_list(
        "district", flat=True
    ).distinct()
    for district_name in distinct_member_districts:
        if district_name:
            district, created = District.objects.get_or_create(name=district_name)
            Member.objects.filter(district=district_name).update(temp_district=district)

    # Migrate Candidate districts
    distinct_candidate_districts = Candidate.objects.values_list(
        "district", flat=True
    ).distinct()
    for district_name in distinct_candidate_districts:
        if district_name:
            district, created = District.objects.get_or_create(name=district_name)
            Candidate.objects.filter(district=district_name).update(
                temp_district=district
            )


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0028_auto_20241107_1820"),
    ]

    operations = [
        migrations.RunPython(migrate_to_temp_district),
    ]
