# Generated by Django 5.0.9 on 2024-11-07 12:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0029_auto_20241107_1822"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="district",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="district",
        ),
    ]
