# Generated by Django 5.0.9 on 2024-11-07 13:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0030_auto_20241107_1825"),
    ]

    operations = [
        migrations.RenameField(
            model_name="member",
            old_name="temp_district",
            new_name="district",
        ),
        migrations.RenameField(
            model_name="candidate",
            old_name="temp_district",
            new_name="district",
        ),
    ]
