# Generated by Django 5.0.9 on 2024-11-13 08:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0031_auto_20241107_1834"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\+?1?\\d{9,15}$", message="Enter a valid phone number."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="district",
            name="name",
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
